### PR TITLE
Add Go as a target language to the context menu

### PR DESCRIPTION
**Pull request by generalmimon**
See https://github.com/kaitai-io/kaitai_struct/issues/146#issuecomment-586013026

It would be fine to also update the list of the supported languages for generating code feature in the wiki: https://github.com/kaitai-io/kaitai_struct_webide/wiki/Features#generate-file-parser-for-your-favorite-language.

### CODE REVIEW

**Comment by generalmimon** [comment]
@GreyCat @koczkatamas

**Comment by GreyCat** [comment]
Let's give Tamás several more days to review? If that will take too long, feel free to merge.

**Comment by GreyCat** [comment]
Merging in, thanks!.

**Comment by koczkatamas** [comment]
Uh sorry, I  could not comment previously and I forgot, but LGTM.

**Pull request merged**
